# tags: kali
[kalitest-distrobox]
home="${HOME}"/Distrobox/kalitest-distrobox
hostname="$(uname -n)"
image=docker.io/kalilinux/kali-rolling:latest
additional_flags="-p=8400:8400"
unshare_netns=true
replace=true
start_now=true

# tags: generic java
[javadev-distrobox]
home="${HOME}"/Distrobox/javadev-distrobox
hostname="$(uname -n)"
image=quay.io/toolbx-images/debian-toolbox:12
# additional_flags="-p=8200-8300:8200-8300 -p 5005:5005 -p 9010:9010"
# unshare_netns=true
replace=true
start_now=true

# tags: generic postgresql
[postgresql-distrobox]
home="${HOME}"/Distrobox/postgresql-distrobox
hostname="$(uname -n)"
image=quay.io/toolbx-images/debian-toolbox:12
# additional_flags="-p=5432:5432"
additional_packages="systemd libpam-systemd pipewire-audio-client-libraries"
# unshare_netns=true
init=true
replace=true
start_now=true

# tags: generic
[debiantest-distrobox]
home="${HOME}"/Distrobox/debiantest-distrobox 
image=quay.io/toolbx-images/debian-toolbox:12
replace=true
start_now=true

[veracrypt-distrobox]
home="${HOME}"/Distrobox/veracrypt-distrobox 
image=quay.io/toolbx-images/debian-toolbox:12
root=true
replace=true
start_now=true

[fedoratest-distrobox]
home="${HOME}"/Distrobox/fedoratest-distrobox
image=quay.io/fedora/fedora:41
replace=true
start_now=true

# tags: generic
[archtest-distrobox]
home="${HOME}"/Distrobox/mobiletest-distrobox
image=docker.io/library/archlinux:latest
root=true
replace=true
start_now=true
